### ISSUE TITLE
Auction Flipper making very unusual prices. 

### ISSUE THREAD

**Issue by ghost** [Siddharth3141/Hypixel_Skyblock_Auction_Flipper#4]
When running the flipper, the program creates odd prices that wouldn't normally make sense when you flip items. For example., I got "2,1m flip" for a young dragon armor boots which just wouldn't work in reality. Is there something wrong with the code that has to be fix or is there something wrong with the config.json file(params for me are 10, 50).

P.S. : Its also including youtuber's names, so is that cake souls?

Sincerely,
VD

**Comment by Overthrowing** [comment]
I believe this is caused by the derpy mayor because it causes the API to basically freak out and yes the youtuber names are cake souls.

**Comment by vivandoshi2008** [comment]
Ooh okay. Also, what params do you recommend to filter through the junk like Decoys. Also, is it really caused by Derpy since the website looks for the second lowest price in the api which therefore wouldn't show any crazy change. And, the software shows me stuff from like few days ago, how do I fix that? 

Thanks,
VD
